[package]
name = "protobufs"
version = "0.1.0"
authors = ["Alex Newman <posix4e@gmail.com>"]
build = "build.rs"

[dependencies]
protobuf = "~1.0.13"

[build-dependencies.protobuf_build]
git = "https://github.com/plietar/rust-protobuf-build.git"
